######################## default configuration ####################
baseURL = "https://devl-cybhero-network.netlify.app/"
title = "Cyber Hero Network"
theme = "bizcraft-hugo"
# post pagination
paginate = "3"
# post excerpt
summaryLength = "10"
# google analytics
googleAnalytics = "" # example : UA-123-45
# disqus short name
disqusShortname = "#" # get your shortname form here : https://disqus.com
disableLiveReload = true


############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS"]

[markup.goldmark.renderer]
unsafe= true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/fontawesome/font-awesome.min.css"
[[params.plugins.css]]
link = "plugins/animate.css"
[[params.plugins.css]]
link = "plugins/prettyPhoto.css"
[[params.plugins.css]]
link = "plugins/owl/owl.carousel.css"
[[params.plugins.css]]
link = "plugins/owl/owl.theme.css"
[[params.plugins.css]]
link = "plugins/flex-slider/flexslider.css"
[[params.plugins.css]]
link = "plugins/cd-hero/cd-hero.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/style-switcher.js"
[[params.plugins.js]]
link = "plugins/owl/owl.carousel.js"
[[params.plugins.js]]
link = "plugins/jquery.prettyPhoto.js"
[[params.plugins.js]]
link = "plugins/flex-slider/jquery.flexslider.js"
[[params.plugins.js]]
link = "plugins/cd-hero/cd-hero.js"
[[params.plugins.js]]
link = "plugins/isotope.js"
[[params.plugins.js]]
link = "plugins/ini.isotope.js"
[[params.plugins.js]]
link = "plugins/wow.min.js"
[[params.plugins.js]]
link = "plugins/jquery.easing.1.3.js"
[[params.plugins.js]]
link = "plugins/jquery.counterup.min.js"
[[params.plugins.js]]
link = "plugins/waypoints.min.js"


############################## English navigation ###############################

[[Languages.en.menu.main]]
name = "Show"
URL = "show"
weight = 2

[[Languages.en.menu.main]]
name = "Comics"
URL = "comics"
weight = 3

[[Languages.en.menu.main]]
name = "Videos"
URL = "video"
weight = 4

[[Languages.en.menu.main]]
name = "About"
URL = "about"
weight = 5

[[Languages.en.menu.main]]
name = "Contact"
URL = "contact"
weight = 6

[[Languages.en.menu.main]]
name = "Shop"
URL = "https://cyberherocomics.itemorder.com/sale"
weight = 7

[[Languages.en.menu.main]]
name = "Join the Show"
URL = "show"
weight = 8



############################## French navigation ###############################

[[Languages.fr.menu.main]]
name = "About"
URL = "about"
weight = 2

[[Languages.fr.menu.main]]
name = "Portfolio"
URL = "portfolio"
weight = 3

[[Languages.fr.menu.main]]
name = "Blog"
URL = "blog"
weight = 4

[[Languages.fr.menu.main]]
weight = 5
name = "Pages"
hasChildren = true

  [[Languages.fr.menu.main]]
  parent = "Pages"
  name = "Career"
  URL = "career"

  [[Languages.fr.menu.main]]
  parent = "Pages"
  name = "Service"
  URL = "service"

  [[Languages.fr.menu.main]]
  parent = "Pages"
  name = "Team"
  URL = "team"

  [[Languages.fr.menu.main]]
  parent = "Pages"
  name = "FAQ"
  URL = "faq"

  [[Languages.fr.menu.main]]
  parent = "Pages"
  name = "Pricing"
  URL = "pricing"
  
[[Languages.fr.menu.main]]
name = "Contact"
URL = "contact"
weight = 6



#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "This is meta description"
author = "Themefisher"
# contact info
address = "9567 Turner Trace Apt. BC C3G8A4"
phone = "+211234565523"
email = "info@bexer.com"
# contact form action
contact_form_action = "https://formspree.io/f/xayalrwr" # contact form works with https://formspree.io
# copyright
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"

# flickr photos
[[params.flickr_photos]]
image = "images/gallery/1.jpg"
[[params.flickr_photos]]
image = "images/gallery/2.jpg"
[[params.flickr_photos]]
image = "images/gallery/3.jpg"
[[params.flickr_photos]]
image = "images/gallery/4.jpg"
[[params.flickr_photos]]
image = "images/gallery/5.jpg"
[[params.flickr_photos]]
image = "images/gallery/6.jpg"
[[params.flickr_photos]]
image = "images/gallery/7.jpg"
[[params.flickr_photos]]
image = "images/gallery/8.jpg"
[[params.flickr_photos]]
image = "images/gallery/9.jpg"

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
  
############################# social site ########################

[[params.social]]
name = "linkedin"
icon = "fa-linkedin-square" # fontawesome icon pack 4.7 | https://fontawesome.com/v4.7.0/icons/
link = "https://www.linkedin.com/in/gary-berman-8aa36475/"

[[params.social]]
name = "youtube"
icon = "fa-youtube-play" # fontawesome icon pack 4.7 | https://fontawesome.com/v4.7.0/icons/
link = "https://www.youtube.com/channel/UCXKaP2I5ZLmxMzjbrxZMWjw"

[[params.social]]
name = "twitter"
icon = "fa-twitter" # fontawesome icon pack 4.7 | https://fontawesome.com/v4.7.0/icons/
link = "https://twitter.com/UnsungCyberHero"

############################# widget 1 footer ########################

[[params.widget_footer_1]]
label = "Become A Patreon"
name = "Join our mission to shine the light on the “Unsung ​Heroes” of the Digital Universe!"
link = "https://www.patreon.com/garylberman?fan_landing=true"

[params.widget_footer_2]
name = "Useful Links"

################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
# footer content
footer_content = "We are a awward winning multinational company. We believe in quality and standard worldwide."
# copyright
copyright = "Copyright © 2021 CyberHeroes. All Rights Reserved. | Built by [Supremely](https://supremelytech.com/)"

################################### French language #####################################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2
home = "Accueil"
# footer content
footer_content = "We are a awward winning multinational company. We believe in quality and standard worldwide."
# copyright
copyright = "Copyright © 2021 CyberHeroes. All Rights Reserved. | Built by [Supremely](https://supremelytech.com/)"