---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Blog Post
- type: document
  path: exampleSite/content/blog/_index.md
  label: Blog Page
- type: directory
  path: exampleSite/content/blog
  label: All Post
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - post
- type: heading
  label: Author
- type: directory
  path: exampleSite/content/author
  label: Author
  create: documents
  match: "**/*"
  templates:
  - author
- type: heading
  label: Service
- type: document
  path: exampleSite/content/service/_index.md
  label: Service Page
- type: document
  path: exampleSite/data/service.yml
  label: Service Data
- type: heading
  label: Portfolio
- type: document
  path: exampleSite/content/portfolio/_index.md
  label: Portfolio Page
- type: directory
  path: exampleSite/content/portfolio
  label: Portfolio Items
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - portfolio
- type: heading
  label: Career
- type: document
  path: exampleSite/content/career/_index.md
  label: Career Page
- type: document
  path: exampleSite/data/career.yml
  label: Career Content
- type: heading
  label: About
- type: document
  path: exampleSite/data/about.yml
  label: About Content
- type: document
  path: exampleSite/content/about/_index.md
  label: About Page
- type: heading
  label: Pricing
- type: document
  path: exampleSite/content/pricing/_index.md
  label: Pricing Page
- type: document
  path: exampleSite/data/pricing.yml
  label: Pricing Table
- type: heading
  label: Team
- type: document
  path: exampleSite/content/team/_index.md
  label: Team Page
- type: document
  path: exampleSite/data/team.yml
  label: Team Members
- type: heading
  label: FAQ
- type: document
  path: exampleSite/content/faq/_index.md
  label: FAQ Page
- type: heading
  label: Contact
- type: document
  path: exampleSite/content/contact/_index.md
  label: Contact Page
- type: heading
  label: All Page Content & Data
- type: directory
  path: exampleSite/content
  label: All Page
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/data
  label: All Data
  create: all
  match: "**/*"
- type: heading
  label: Configuration
- type: directory
  path: exampleSite
  label: Configuration
  create: all
  match: "*.toml"
  new_doc_ext: toml
upload_dir: exampleSite/static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.58.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.58.2
